[tool.poetry]
name = "intro-to-algorithms"
version = "0.1.0"
description = ""
authors = ["Mihajlo Madic <mihajlomadic@diffine.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
